application: halfpotch-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
# data
- url: /data/.*
  script: core.data.app

# mosaic maker
- url: /mosaicmaker/?
  static_files: mosaicmaker/mosaicmaker.html
  upload: mosaicmaker/mosaicmaker\.html

# optimizer
- url: /optimizer/?
  static_files: optimizer/optimizer.html
  upload: optimizer/optimizer\.html

- url: /optimizer/app/.*
  script: optimizer.optimizer.app

# logger
- url: /logger/?
  static_files: logger/app.html
  upload: logger/app\.html

- url: /logger/app/.*
  script: logger.app.app

# index
- url: /
  static_files: index.html
  upload: index.html

# other public files
- url: /(.*/.*\.(js|css|html))
  static_files: \1
  upload: .*/.*\.(js|css|html)


libraries:
- name: webapp2
  version: "2.5.2"