application: halfpotch
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /mosaic
  static_files: mosaicmaker.html
  upload: mosaicmaker\.html

- url: /optimizer
  static_files: optimizer.html
  upload: optimizer\.html

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*/.*\.(js|css))
  static_files: \1
  upload: .*/.*\.(js|css)

# debug
- url: /test/(.)\.txt
  static_files: test/\1.txt
  upload: test/.*

- url: /script/.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
