application: halfpotch-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /mosaicmaker/?
  static_files: mosaicmaker/mosaicmaker.html
  upload: mosaicmaker/mosaicmaker\.html

- url: /optimizer/?
  static_files: optimizer/optimizer.html
  upload: optimizer/optimizer\.html

- url: /optimizer/app/.*
  script: optimizer.optimizer.app

- url: /logger/?
  static_files: logger/logger.html
  upload: logger/logger\.html

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*/.*\.(js|css|html))
  static_files: \1
  upload: .*/.*\.(js|css|html)

libraries:
- name: webapp2
  version: "2.5.2"