runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
# data
- url: /data/.*
  script: core.data.app

# mosaic maker
- url: /mosaicmaker/?
  static_files: mosaicmaker/mosaicmaker.html
  upload: mosaicmaker/mosaicmaker\.html

# optimizer
- url: /optimizer/?
  static_files: optimizer/optimizer.html
  upload: optimizer/optimizer\.html

- url: /optimizer/app/.*
  script: optimizer.optimizer.app

# logger
- url: /logger/?
  static_files: logger/app.html
  upload: logger/app\.html

- url: /logger/log(in|out)
  script: logger.api.app

- url: /logger/api/.*
  script: logger.api.app

- url: /_ah/mail/.*
  script: logger.api.app
  login: admin

# index
- url: /
  static_files: index.html
  upload: index.html

# other public files
- url: /(.*/.*\.(js|css|png|html))
  static_files: \1
  upload: .*/.*\.(js|css|png|html)

- url: /halfpotch-ext.crx
  static_files: halfpotch-ext.crx
  upload: halfpotch-ext\.crx

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon\.ico


libraries:
- name: webapp2
  version: "2.5.2"
