// Generated by CoffeeScript 1.6.0
(function() {
  var $, Assoc, CartSelectView, Color, ColorSelectView, DataLoader, DataProcessor, ELSE, FormView, IF, Model, PartImageView, ProgressButton, ResultView, Retention, Searcher, SelectModel, SelectView, StoreDataLoader, SuperArray, View, escapeHTML, uuid, xhrget,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $ = function(id) {
    return document.getElementById(id);
  };

  escapeHTML = (function() {
    var re, replacer;
    re = /[&<>'"]/g;
    replacer = function(x) {
      return '&#' + x.charCodeAt(0) + ';';
    };
    return function(text) {
      return text.replace(re, replacer);
    };
  })();

  SuperArray = (function(_super) {

    __extends(SuperArray, _super);

    function SuperArray(ary) {
      if (ary == null) {
        ary = [];
      }
      Array.prototype.push.apply(this, ary);
    }

    SuperArray.prototype.minBy = function(func) {
      var d, min, res, solution, _i, _len, _ref;
      min = Infinity;
      solution = null;
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        d = this[_i];
        res = func(d);
        if (min > res) {
          _ref = [res, d], min = _ref[0], solution = _ref[1];
        }
      }
      return solution;
    };

    SuperArray.prototype.maxBy = function(func) {
      return this.minBy(function(d) {
        return -func(d);
      });
    };

    SuperArray.prototype.min = function() {
      return Math.min.apply(Math, this);
    };

    SuperArray.prototype.max = function() {
      return Math.max.apply(Math, this);
    };

    SuperArray.prototype.combinations = function(len) {
      var a, i, last, res, _i, _j, _len, _len1, _ref;
      if (!len) {
        return [[]];
      }
      res = [];
      for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
        a = this[i];
        _ref = SuperArray.prototype.combinations.call(this.slice(i + 1), len - 1);
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          last = _ref[_j];
          res.push([a].concat(last));
        }
      }
      return res;
    };

    return SuperArray;

  })(Array);

  uuid = (function() {
    var re, replacer;
    re = /[xy]/g;
    replacer = function(c) {
      var r;
      r = Math.random() * 16 | 0;
      return (c === 'x' ? r : r & 3 | 8).toString(16);
    };
    return function() {
      return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(re, replacer).toUpperCase();
    };
  })();

  Model = (function() {

    function Model() {
      this._uuid = uuid();
    }

    Model.prototype.change = function() {
      var arg, name;
      name = arguments[0], arg = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (name == null) {
        name = 'change';
      }
      return eve.apply(null, ["" + this._uuid + "." + name, null].concat(__slice.call(arg)));
    };

    Model.prototype.listen = function(name, func) {
      if (name == null) {
        name = 'change';
      }
      if (arguments.length === 1) {
        func = name;
        name = 'change';
      }
      return eve.on("" + this._uuid + "." + name, func.bind(this));
    };

    return Model;

  })();

  View = (function() {

    function View(model) {
      var _this = this;
      this.model = model;
      model.listen(function() {
        var arg;
        arg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return _this.render.apply(_this, arg);
      });
    }

    View.prototype.render = function() {};

    return View;

  })();

  Color = (function() {

    function Color(r, g, b) {
      this.r = r != null ? r : 0;
      this.g = g != null ? g : 0;
      this.b = b != null ? b : 0;
    }

    Color.prototype.dist = function(color) {
      var db, dg, dr, _ref;
      _ref = [color.r - this.r, color.g - this.g, color.b - this.b], dr = _ref[0], dg = _ref[1], db = _ref[2];
      return Math.sqrt(dr * dr + dg * dg + db * db);
    };

    Color.prototype.luma = function() {
      return this.r * 0.3 + this.g * 0.59 + this.b * 0.11;
    };

    Color.prototype.toArray = function() {
      return [this.r, this.g, this.b];
    };

    Color.prototype.toString = function() {
      return "rgb(" + this.r + ", " + this.g + ", " + this.b + ")";
    };

    return Color;

  })();

  Assoc = (function(_super) {

    __extends(Assoc, _super);

    function Assoc(map) {
      this.map = map != null ? map : {};
      Assoc.__super__.constructor.apply(this, arguments);
    }

    Assoc.prototype.keys = function() {
      return Object.keys(this.map);
    };

    Assoc.prototype.get = function(name) {
      return this.map[name];
    };

    Assoc.prototype.set = function(name, value) {
      this.map[name] = value;
      return this.change('change', name, value);
    };

    return Assoc;

  })(Model);

  FormView = (function(_super) {

    __extends(FormView, _super);

    function FormView(model, elem) {
      var input, _i, _len, _ref,
        _this = this;
      this.elem = elem;
      FormView.__super__.constructor.apply(this, arguments);
      _ref = HTMLElement.prototype.querySelectorAll.call(elem, '[name]');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        input = _ref[_i];
        this._setValue(input);
      }
      HTMLElement.prototype.addEventListener.call(elem, 'change', function(e) {
        return _this._setValue(e.target);
      }, false);
    }

    FormView.prototype._setValue = function(input) {
      var name, value, _ref;
      name = input.name, value = input.value;
      switch ((_ref = input.getAttribute('type')) != null ? _ref.toLowerCase() : void 0) {
        case 'number':
        case 'range':
          return this.model.set(name, +value || 0);
        case 'date':
        case 'datetime-local':
          return this.model.set(name, new Date(value));
        case 'checkbox':
          return this.model.set(name, input.checked);
        case 'radio':
          if (input.checked) {
            return this.model.set(name, value);
          }
          break;
        default:
          return this.model.set(name, value);
      }
    };

    FormView.prototype.render = function() {
      var input, inputs, name, value, _i, _j, _len, _len1, _ref;
      _ref = this.model.keys();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        name = _ref[_i];
        inputs = HTMLFormElement.prototype.querySelectorAll.call(this.elem, "[name=" + name + "]");
        if (!inputs.length) {
          continue;
        }
        value = this.model.get(name);
        switch (inputs[0].type) {
          case 'checkbox':
            inputs[0].checked = value;
            break;
          case 'radio':
            value = value.toString();
            for (_j = 0, _len1 = inputs.length; _j < _len1; _j++) {
              input = inputs[_j];
              if (!(input.value === value)) {
                continue;
              }
              input.checked = true;
              break;
            }
            break;
          default:
            inputs[0].value = value;
        }
      }
    };

    return FormView;

  })(View);

  Retention = (function() {
    var ELSE, IF, NOT, UNLESS, WHEN;

    Retention.IF = IF = function(ret) {
      return function(success, fail) {
        if (ret.resolved) {
          if (typeof success === "function") {
            success();
          }
        } else if (ret.rejected) {
          if (typeof fail === "function") {
            fail();
          }
        } else {
          success && ret.successCallbacks.push(success);
          fail && ret.failCallbacks.push(fail);
        }
        return ret;
      };
    };

    Retention.UNLESS = UNLESS = function(ret) {
      return function(fail, success) {
        return IF(ret)(success, fail);
      };
    };

    Retention.ELSE = ELSE = function(x) {
      return x;
    };

    Retention.NOT = NOT = function(ret) {
      var r;
      r = new Retention();
      IF(ret)(function() {
        return r.reject(ret.result);
      });
      UNLESS(ret)(function() {
        return r.resolve(ret.error);
      });
      return r;
    };

    Retention.WHEN = WHEN = function(ret) {
      return function(callback) {
        return IF(ret)(callback, callback);
      };
    };

    Retention.prototype.result = null;

    Retention.prototype.error = null;

    Retention.prototype.resolved = false;

    Retention.prototype.rejected = false;

    function Retention() {
      this.successCallbacks = [];
      this.failCallbacks = [];
    }

    Retention.prototype.resolve = function(result) {
      var f, _i, _len, _ref;
      if (this.resolved || this.rejected) {
        return;
      }
      this.resolved = true;
      this.result = result;
      _ref = this.successCallbacks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        f();
      }
    };

    Retention.prototype.reject = function(error) {
      var f, _i, _len, _ref;
      if (this.resolved || this.rejected) {
        return;
      }
      this.rejected = true;
      this.error = error;
      _ref = this.failCallbacks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        f();
      }
    };

    Retention.prototype.AND = function(ret) {
      var r,
        _this = this;
      r = new Retention();
      IF(this)(function() {
        return IF(ret)(function() {
          return r.resolve();
        });
      });
      IF(ret)(function() {
        return IF(_this)(function() {
          return r.resolve();
        });
      });
      UNLESS(this)(function() {
        return r.reject();
      });
      UNLESS(ret)(function() {
        return r.reject();
      });
      return r;
    };

    Retention.prototype.DAND = function(ret) {
      var r,
        _this = this;
      r = new Retention();
      IF(this)(function() {
        return IF(ret)(function() {
          return r.resolve();
        });
      });
      IF(ret)(function() {
        return IF(_this)(function() {
          return r.resolve();
        });
      });
      UNLESS(this)(function() {
        return WHEN(ret)(function() {
          return r.reject();
        });
      });
      UNLESS(ret)(function() {
        return WHEN(_this)(function() {
          return r.reject();
        });
      });
      return r;
    };

    Retention.prototype.OR = function(ret) {
      var r,
        _this = this;
      r = new Retention();
      IF(this)(function() {
        return r.resolve();
      });
      IF(ret)(function() {
        return r.resolve();
      });
      UNLESS(this)(function() {
        return UNLESS(ret)(function() {
          return r.reject();
        });
      });
      UNLESS(ret)(function() {
        return UNLESS(_this)(function() {
          return r.reject();
        });
      });
      return r;
    };

    Retention.prototype.DOR = function(ret) {
      var r,
        _this = this;
      r = new Retention();
      IF(this)(function() {
        return WHEN(ret)(function() {
          return r.resolve();
        });
      });
      IF(ret)(function() {
        return WHEN(_this)(function() {
          return r.resolve();
        });
      });
      UNLESS(this)(function() {
        return UNLESS(ret)(function() {
          return r.reject();
        });
      });
      UNLESS(ret)(function() {
        return UNLESS(_this)(function() {
          return r.reject();
        });
      });
      return r;
    };

    return Retention;

  })();

  IF = Retention.IF, ELSE = Retention.ELSE;

  xhrget = function(url, param) {
    var k, r, xhr;
    if (param) {
      url += '?' + ((function() {
        var _i, _len, _ref, _results;
        _ref = Object.keys(param);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          k = _ref[_i];
          _results.push("" + k + "=" + param[k]);
        }
        return _results;
      })()).join('&');
    }
    r = new Retention();
    xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.onload = function() {
      return r.resolve(xhr.responseText);
    };
    xhr.onerror = function() {
      return r.reject(xhr.statusText);
    };
    xhr.send();
    return r;
  };

  DataLoader = (function() {
    var source;

    function DataLoader() {}

    source = ['test/3.txt', 'test/5.txt', 'test/0.txt'];

    DataLoader.prototype.load = function(callback, errorCallback) {
      var categories, codesData, colorNames, colors, colorsData, parts, partsData;
      colors = {};
      colorNames = {};
      parts = {};
      categories = {};
      colorsData = this.get(source[0]);
      codesData = this.get(source[1]);
      partsData = this.get(source[2]);
      return IF(colorsData.AND(codesData.AND(partsData)))(function() {
        var category, categoryId, categoryName, color, colorId, colorName, id, name, part, rrggbb, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
        _ref = colorsData.result;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          _ref1 = _ref[_i], colorId = _ref1[0], colorName = _ref1[1], rrggbb = _ref1[2];
          colors[colorId] = colorNames[colorName] = {
            id: colorId,
            name: colorName,
            rgb: '#' + rrggbb
          };
        }
        _ref2 = codesData.result;
        for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
          _ref3 = _ref2[_j], id = _ref3[0], colorName = _ref3[1];
          part = parts[id] || (parts[id] = {
            id: id,
            colors: []
          });
          color = colorNames[colorName];
          if (__indexOf.call(part.colors, color) < 0) {
            part.colors.push(color);
          }
        }
        _ref4 = partsData.result;
        for (_k = 0, _len2 = _ref4.length; _k < _len2; _k++) {
          _ref5 = _ref4[_k], categoryId = _ref5[0], categoryName = _ref5[1], id = _ref5[2], name = _ref5[3];
          part = parts[id];
          if (!part) {
            continue;
          }
          category = categories[categoryId] || (categories[categoryId] = {
            id: categoryId,
            name: categoryName,
            parts: []
          });
          part.name = name;
          part.categoryId = categoryId;
          category.parts.push(part);
        }
        return callback({
          categories: categories,
          parts: parts,
          colors: colors
        });
      }, ELSE(function() {
        return typeof errorCallback === "function" ? errorCallback() : void 0;
      }));
    };

    DataLoader.prototype.get = function(url) {
      var data, r;
      r = new Retention();
      data = xhrget(url);
      IF(data)(function() {
        var line;
        return r.resolve((function() {
          var _i, _len, _ref, _results;
          _ref = data.result.split('\n');
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            line = _ref[_i];
            _results.push(line.split('\t'));
          }
          return _results;
        })());
      }, ELSE(function() {
        return r.reject();
      }));
      return r;
    };

    return DataLoader;

  })();

  StoreDataLoader = (function() {
    var baseurl;

    function StoreDataLoader() {}

    baseurl = '/script/getstoredata';

    StoreDataLoader.prototype.load = function(callback, errorCallback, params) {
      var data, param;
      data = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          param = params[_i];
          _results.push(xhrget(baseurl, param));
        }
        return _results;
      })();
      return IF(data.reduce(function(pre, cur) {
        return pre.AND(cur);
      }))(function() {
        var d, result;
        result = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            d = data[_i];
            _results.push(JSON.parse(d.result));
          }
          return _results;
        })();
        return callback(result);
      }, ELSE(function() {
        return errorCallback();
      }));
    };

    return StoreDataLoader;

  })();

  SelectModel = (function(_super) {

    __extends(SelectModel, _super);

    function SelectModel(type) {
      this.type = type;
      SelectModel.__super__.constructor.apply(this, arguments);
      this.item = null;
      this.options = [];
    }

    SelectModel.prototype.reset = function(source) {
      var id, ids, _i, _len;
      this.options = [];
      ids = Object.keys(source).sort(function(a, b) {
        return source[a].name.localeCompare(source[b].name);
      });
      for (_i = 0, _len = ids.length; _i < _len; _i++) {
        id = ids[_i];
        this.add(source[id], false);
      }
      return this.change();
    };

    SelectModel.prototype.add = function(item, change) {
      if (change == null) {
        change = true;
      }
      this.options.push(item);
      if (change) {
        return this.change('add', item);
      }
    };

    SelectModel.prototype.remove = function() {
      var idx, item;
      item = this.item;
      this.item = null;
      idx = this.options.indexOf(item);
      this.options.splice(idx, 1);
      this.change();
      return item;
    };

    SelectModel.prototype.setItem = function(id) {
      var option, _i, _len, _ref;
      _ref = this.options;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        if (option.id === id) {
          this.item = option;
          this.change('select', option);
          return;
        }
      }
    };

    return SelectModel;

  })(Model);

  SelectView = (function(_super) {

    __extends(SelectView, _super);

    function SelectView(model, elem) {
      this.elem = elem;
      SelectView.__super__.constructor.apply(this, arguments);
      model.listen('add', this.add.bind(this));
    }

    SelectView.prototype._createLi = function(item) {
      var id, li, type;
      type = escapeHTML(this.model.type);
      id = escapeHTML(item.id);
      li = document.createElement('li');
      li.insertAdjacentHTML('beforeend', "<input type=\"radio\" id=\"" + (type + id) + "\" name=\"" + type + "\" value=\"" + id + "\">\n<label for=\"" + (type + id) + "\">" + (escapeHTML(item.name)) + "</label>");
      return li;
    };

    SelectView.prototype.add = function(option) {
      return this.elem.appendChild(this._createLi(option));
    };

    SelectView.prototype.render = function() {
      var frag, option, _i, _len, _ref;
      this.elem.innerHTML = '';
      frag = document.createDocumentFragment();
      _ref = this.model.options;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        frag.appendChild(this._createLi(option));
      }
      return this.elem.appendChild(frag);
    };

    return SelectView;

  })(View);

  ColorSelectView = (function(_super) {

    __extends(ColorSelectView, _super);

    function ColorSelectView() {
      return ColorSelectView.__super__.constructor.apply(this, arguments);
    }

    ColorSelectView.prototype._createLi = function(item) {
      var id, li;
      id = escapeHTML(item.id);
      li = document.createElement('li');
      li.insertAdjacentHTML('beforeend', "<input type=\"radio\" id=\"color" + id + "\" name=\"color\" value=\"" + id + "\">\n<label for=\"color" + id + "\">\n  <span class=\"color-box\"\n    style=\"background-color: " + (escapeHTML(item.rgb)) + ";\"></span>\n  " + (escapeHTML(item.name)) + "\n</label>");
      return li;
    };

    return ColorSelectView;

  })(SelectView);

  CartSelectView = (function(_super) {

    __extends(CartSelectView, _super);

    function CartSelectView() {
      return CartSelectView.__super__.constructor.apply(this, arguments);
    }

    CartSelectView.prototype._createLi = function(item) {
      var id, li, text;
      id = escapeHTML(item.id);
      text = escapeHTML("(" + item.amount + "x) " + item.color.name + " " + item.part.name);
      li = document.createElement('li');
      li.insertAdjacentHTML('beforeend', "<input type=\"radio\" id=\"cart" + id + "\" name=\"cart\" value=\"" + id + "\">\n<label for=\"cart" + id + "\">\n  <span class=\"color-box\"\n    style=\"background-color: " + (escapeHTML(item.color.rgb)) + ";\"></span>\n  " + text + "\n</label>");
      return li;
    };

    return CartSelectView;

  })(SelectView);

  PartImageView = (function(_super) {

    __extends(PartImageView, _super);

    function PartImageView(model, elem) {
      var img;
      this.elem = elem;
      PartImageView.__super__.constructor.apply(this, arguments);
      img = document.createElement('img');
      elem.appendChild(img);
      model.listen('select', function(item) {
        var colorId;
        colorId = item.colors[0].id;
        img.onerror = function() {
          this.src = "http://img.bricklink.com/P/" + colorId + "/" + item.id + ".jpg";
          return this.onerror = null;
        };
        return img.src = "http://img.bricklink.com/P/" + colorId + "/" + item.id + ".gif";
      });
    }

    return PartImageView;

  })(View);

  DataProcessor = (function(_super) {

    __extends(DataProcessor, _super);

    function DataProcessor() {
      DataProcessor.__super__.constructor.apply(this, arguments);
      this.items = [];
      this.stores = [];
      this.matrix = new ItemStoreMatrix();
      this._loader = new StoreDataLoader();
      this._solver = new Solver();
    }

    DataProcessor.prototype.reset = function() {
      this.items = [];
      return this.change('reset');
    };

    DataProcessor.prototype.process = function(items) {
      var item, params,
        _this = this;
      this.items = items;
      params = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          _results.push({
            part: item.part.id,
            color: item.color.id,
            amount: item.amount
          });
        }
        return _results;
      })();
      this._loader.load(function(data) {
        _this.makeMatrix(data);
        _this.result = _this._solver.solve(_this.items, _this.stores, _this.matrix);
        return _this.change();
      }, function() {
        return _this.change('error');
      }, params);
      return this.change('start');
    };

    DataProcessor.prototype.makeMatrix = function(storeData) {
      var id, item, key, s, sData, store, storeMap, _i, _j, _len, _len1, _name;
      storeMap = {};
      for (id = _i = 0, _len = storeData.length; _i < _len; id = ++_i) {
        sData = storeData[id];
        item = this.items[id];
        item.stores = [];
        for (_j = 0, _len1 = sData.length; _j < _len1; _j++) {
          s = sData[_j];
          store = storeMap[_name = s.id] || (storeMap[_name] = {
            id: s.id,
            name: s.name,
            items: []
          });
          store.items.push(item);
          item.stores.push(store);
          this.matrix.set(item, store, {
            price: s.price,
            url: s.url
          });
        }
      }
      return this.stores = (function() {
        var _k, _len2, _ref, _results;
        _ref = Object.keys(storeMap);
        _results = [];
        for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
          key = _ref[_k];
          _results.push(storeMap[key]);
        }
        return _results;
      })();
    };

    return DataProcessor;

  })(Model);

  ResultView = (function(_super) {

    __extends(ResultView, _super);

    function ResultView(model, elem) {
      this.elem = elem;
      ResultView.__super__.constructor.apply(this, arguments);
      model.listen('reset', this.hide.bind(this));
      this.showing = false;
    }

    ResultView.prototype._td = function(text) {
      var td;
      td = document.createElement('td');
      td.appendChild(document.createTextNode(text));
      return td;
    };

    ResultView.prototype._createRow = function(item, store) {
      var price, text, tr, url, _ref;
      _ref = this.model.matrix.get(item, store), price = _ref.price, url = _ref.url;
      text = escapeHTML(item.color.name + ' ' + item.part.name);
      tr = document.createElement('tr');
      tr.insertAdjacentHTML('beforeend', "<td>\n  <span class=\"color-box\"\n    style=\"background-color: " + (escapeHTML(item.color.rgb)) + ";\"></span>\n  " + text + "\n</td>\n<td>\n  <a href=\"http://www.bricklink.com" + (escapeHTML(url)) + "\" target=\"_blank\">\n    " + (escapeHTML(store.name)) + "\n  </a>\n</td>");
      tr.appendChild(this._td(price));
      tr.appendChild(this._td(item.amount));
      tr.appendChild(this._td((price * item.amount).toFixed(2)));
      return tr;
    };

    ResultView.prototype._createTable = function(solution) {
      var footer, frag, header, i, item, store, wholePrice, _i, _len;
      frag = document.createDocumentFragment();
      header = document.createElement('tr');
      header.innerHTML = '<th>部品</th><th>店名</th><th>単価（円）</th><th>個数</th><th>小計</th>';
      frag.appendChild(header);
      wholePrice = 0;
      for (i = _i = 0, _len = solution.length; _i < _len; i = ++_i) {
        store = solution[i];
        item = this.model.items[i];
        frag.appendChild(this._createRow(item, store));
        wholePrice += this.model.matrix.get(item, store).price * item.amount;
      }
      footer = document.createElement('tr');
      footer.innerHTML = "<td colspan='3'><td>合計</td><td><b>" + (wholePrice.toFixed(2)) + "</b></td>";
      frag.appendChild(footer);
      return frag;
    };

    ResultView.prototype.hide = function() {
      this.elem.className = '';
      return this.showing = false;
    };

    ResultView.prototype.render = function() {
      var solution, table, tbody, _i, _len, _ref;
      if (!this.model.result.length) {
        return;
      }
      this.elem.innerHTML = '';
      table = document.createElement('table');
      tbody = document.createElement('tbody');
      _ref = this.model.result.slice(0, 20);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        solution = _ref[_i];
        tbody.appendChild(this._createTable(solution));
      }
      table.appendChild(tbody);
      this.elem.appendChild(table);
      this.elem.className = 'displayed';
      return this.showing = true;
    };

    return ResultView;

  })(View);

  ProgressButton = (function(_super) {

    __extends(ProgressButton, _super);

    function ProgressButton(model, elem) {
      this.elem = elem;
      ProgressButton.__super__.constructor.apply(this, arguments);
      model.listen('start', this.start.bind(this));
      model.listen('error', this.error.bind(this));
      model.listen('reset', this.reset.bind(this));
      this.reset();
    }

    ProgressButton.prototype._setBackground = function(color) {
      return this.elem.style.backgroundColor = color;
    };

    ProgressButton.prototype.error = function() {
      this.elem.disabled = false;
      this.elem.value = 'エラー、あとでやり直してください';
      this.elem.className = 'button error';
      return setTimeout(this.reset.bind(this), 3000);
    };

    ProgressButton.prototype.start = function() {
      this.elem.disabled = true;
      return this.elem.value = 'データを集めています...';
    };

    ProgressButton.prototype.reset = function() {
      this.elem.disabled = false;
      this.elem.value = 'このパーツで店を探す';
      return this.elem.className = 'button';
    };

    ProgressButton.prototype.render = function() {
      this.elem.disabled = false;
      if (this.model.result.length) {
        this.elem.value = 'パーツを選びなおす';
        return this.elem.className = 'button';
      } else {
        this.elem.value = 'パーツを減らしてください';
        this.elem.className = 'button error';
        return setTimeout(this.reset.bind(this), 3000);
      }
    };

    return ProgressButton;

  })(View);

  Searcher = (function(_super) {

    __extends(Searcher, _super);

    function Searcher() {
      return Searcher.__super__.constructor.apply(this, arguments);
    }

    Searcher.prototype.setData = function(data) {
      this.data = data;
    };

    Searcher.prototype.tokenize = function(query) {
      return query.split(/[,\s]+/).filter(function(str) {
        return str.length >= 2;
      });
    };

    Searcher.prototype.convertToken = function(token) {
      return token.replace(/([\/\.\d]+)(x)([\/\.\d]*)(x?)([\/\.\d]*)/, function() {
        var arg;
        arg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return arg.slice(1, 6).join(' ').trim();
      }).replace(/\+/g, ' ').toLowerCase();
    };

    Searcher.prototype.score = function(text, tokens) {
      var t, _i, _len;
      if (tokens.length === 0) {
        return 0;
      }
      text = text.toLowerCase();
      for (_i = 0, _len = tokens.length; _i < _len; _i++) {
        t = tokens[_i];
        if (text.indexOf(t) === -1) {
          return 0;
        }
      }
      return 1;
    };

    Searcher.prototype.search = function(query) {
      var id, item, matched, score, scoreMap, t, tokens, _i, _len, _ref;
      tokens = (function() {
        var _i, _len, _ref, _results;
        _ref = this.tokenize(query);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          t = _ref[_i];
          _results.push(this.convertToken(t));
        }
        return _results;
      }).call(this);
      scoreMap = {};
      matched = [];
      _ref = Object.keys(this.data);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        id = _ref[_i];
        item = this.data[id];
        score = this.score(item.name, tokens);
        if (score) {
          scoreMap[id] = score;
          matched.push(item);
        }
      }
      this.options = matched.sort(function(a, b) {
        return scoreMap[b.id] - scoreMap[a.id];
      });
      this.change();
      return this.options;
    };

    return Searcher;

  })(SelectModel);

  (function() {
    var addItem, cart, cartSelect, categorySelect, colorSelect, editItem, partSelect, processor, removeItem, searcher;
    categorySelect = new SelectModel('category');
    partSelect = new SelectModel('part');
    colorSelect = new SelectModel('color');
    cartSelect = new SelectModel('cart');
    cart = new Assoc();
    processor = new DataProcessor();
    searcher = new Searcher('search');
    cart.listen(function(type, id) {
      switch (type) {
        case 'category':
          categorySelect.setItem(id);
          partSelect.reset(categorySelect.item.parts);
          return colorSelect.reset([]);
        case 'part':
          partSelect.setItem(id);
          return colorSelect.reset(partSelect.item.colors);
        case 'color':
          return colorSelect.setItem(id);
        case 'cart':
          return cartSelect.setItem(id);
      }
    });
    addItem = function() {
      var amount, color, part;
      part = partSelect.item;
      color = colorSelect.item;
      amount = cart.get('amount');
      if (part && color && amount) {
        return cartSelect.add({
          id: uuid(),
          part: part,
          color: color,
          amount: amount
        });
      }
    };
    removeItem = function() {
      return cartSelect.remove();
    };
    editItem = function() {
      var amount, color, item, part;
      item = removeItem();
      if (!item) {
        return;
      }
      part = item.part, color = item.color, amount = item.amount;
      cart.set('category', part.categoryId);
      cart.set('part', part.id);
      cart.set('color', color.id);
      return cart.set('amount', amount);
    };
    document.addEventListener('DOMContentLoaded', function() {
      var resultView;
      new SelectView(categorySelect, $('categorySelect'));
      new SelectView(partSelect, $('partSelect'));
      new PartImageView(partSelect, $('image'));
      new ColorSelectView(colorSelect, $('colorSelect'));
      new CartSelectView(cartSelect, $('cart'));
      new FormView(cart, $('form'));
      resultView = new ResultView(processor, $('result'));
      new ProgressButton(processor, $('calculateButton'));
      $('addButton').addEventListener('click', addItem, false);
      $('editButton').addEventListener('click', editItem, false);
      $('removeButton').addEventListener('click', removeItem, false);
      $('calculateButton').addEventListener('click', function() {
        if (resultView.showing) {
          return processor.reset();
        } else {
          return processor.process(cartSelect.options);
        }
      }, false);
      return $('searchBox').addEventListener('input', function() {
        return partSelect.reset(searcher.search(this.value));
      }, false);
    }, false);
    return new DataLoader().load(function(data) {
      categorySelect.reset(data.categories);
      return searcher.setData(data.parts);
    });
  })();

}).call(this);
